---
- name: Install pip
  easy_install: name=pip

- name: Ensure pip is on the latest version
  pip: name=pip state=latest

- name: Install python packages using pip
  pip: name={{ item }} state=latest
  with_items:
    # Development
    - virtualenv
    - virtualenvwrapper
    # Other Environment Utilities
    - powerline-status
