call plug#begin()
Plug 'tpope/vim-sensible'
call plug#end()

" Auto-install missing plugins
autocmd VimEnter *
  \  if !empty(filter(copy(g:plugs), '!isdirectory(v:val.dir)'))
  \|   PlugInstall | q
  \| endif
