---
- name: Check if xcode present
  shell: xcodebuild --help
  register: xcodebuild_exec

- name: Install xcode
  shell: xcode-select --install
  when: xcodebuild_exec.rc != 0

- name: Check if homebrew present
  stat: path=/usr/local/bin/brew
  register: brew_present

- name: Install homebrew
  shell: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  when: brew_present.stat.exists == false

- name: Install homebrew formulas (1/2)
  homebrew: name={{ item }} state=present
  with_items:
    # System Utilities
    - socat
    - htop-osx
    # Shell and Utilities
    - coreutils
    - zsh
    - tmux
    # Version Control
    - git
    - hg
    # Editors
    - vim
    # Development
    - autoconf
    - automake
    - python
    - python3
    - node
    - rbenv
    - ruby-build

- name: Install homebrew formulas (2/2)
  homebrew: name={{ item.name }} install_options={{ item.options }} state=present
  with_items:
    # Editors
    - name: emacs
      options: HEAD,with-cocoa,with-gnutls,with-rsvg,with-imagemagick

- name: Create folder for iTerm2 files
  file: path=~/.iterm2 state=directory

- name: Download iTerm2 shell integration and utilities
  get_url: url={{ item.url }} dest={{ item.dest }} mode=0755
  with_items:
    - url: https://iterm2.com/misc/zsh_startup.in
      dest: ~/.iterm2_shell_integration.zsh
    - url: https://iterm2.com/imgcat
      dest: ~/.iterm2/imgcat
    - url: https://iterm2.com/it2dl
      dest: ~/.iterm2/it2dl
