---
- name: Check if xcode command line tools present
  shell: xcodebuild --help
  register: xcodebuild_exec
  ignore_errors: yes

- name: Install xcode
  shell: xcode-select --install
  when: xcodebuild_exec.rc != 0 and '/Library/Developer/CommandLineTools' not in xcodebuild_exec.stderr

- name: Check if homebrew present
  stat: path=/usr/local/bin/brew
  register: brew_present

- name: Install homebrew
  shell: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  when: not brew_present.stat.exists

- name: Tap into Caskroom fonts
  homebrew_tap: tap=caskroom/fonts state=present

- name: Install homebrew formulas (1/2)
  homebrew: name={{ item }} state=present
  with_items:
    # System Utilities
    - socat
    - htop-osx
    # Shell and Utilities
    - coreutils
    - tmux
    - zsh
    # Version Control
    - git
    - hg
    # Editors
    - vim
    # Development
    - autoconf
    - automake
    - node
    - python
    - python3
    - rbenv
    - ruby-build

- name: Install homebrew formulas (2/2)
  homebrew: name={{ item.name }} install_options={{ item.options }} state=present
  with_items:
    # Editors
    - name: emacs
      options: HEAD,with-cocoa,with-gnutls,with-rsvg,with-imagemagick

- name: Tap into Caskroom versions
  homebrew_tap: tap=caskroom/versions state=present

- name: Install homebrew cask formulas
  homebrew_cask: name={{ item }} state=present
  with_items:
    - font-fira-mono
    - font-fira-mono-for-powerline
    - font-hack
    - font-inconsolata-dz-for-powerline
    - iterm2
    - google-chrome-canary
    - firefoxnightly
    - alfred
    - 1password

- name: Create folder for iTerm2 files
  file: path=~/.iterm2 state=directory

- name: Download iTerm2 shell integration and utilities
  get_url: url={{ item.url }} dest={{ item.dest }} mode=0755
  with_items:
    - url: https://iterm2.com/misc/zsh_startup.in
      dest: ~/.iterm2_shell_integration.zsh
    - url: https://iterm2.com/imgcat
      dest: ~/.iterm2/imgcat
    - url: https://iterm2.com/it2dl
      dest: ~/.iterm2/it2dl
