DOTFILES_BASE=$HOME/.dotfiles

source $HOME/.zsh/antigen/antigen.zsh

antigen use oh-my-zsh

## Load macOS specific bundles
if [[ $OSTYPE == darwin* ]]; then
  antigen bundle osx
fi

## Batch load bundles
antigen bundles <<EOBUNDLES
  git
  zsh-users/zsh-syntax-highlighting
EOBUNDLES

## Must be run after loading the bundles to finalise
antigen apply

## iTerm2 shell integration on macOS (file should be absent otherwise)
test -e "${HOME}/.iterm2_shell_integration.zsh" && \
source "${HOME}/.iterm2_shell_integration.zsh"

test -e "${HOME}/.iterm2/imgcat" && alias imgcat=~/.iterm2/imgcat
test -e "${HOME}/.iterm2/it2dl" && alias it2dl=~/.iterm2/it2dl
