---
- name: Provision Workspace
  hosts: localhost
  connection: local

  vars:
    default_shell: "/bin/zsh"
    current_shell: "{{ ansible_env.SHELL }}"
    default_dotfiles: "{{ ansible_env.HOME }}/.dotfiles"
    playbook_default_location: "{{ default_dotfiles }}/playbooks"
    current_playbook_location: "{{ ansible_env.PWD }}"
    iterm2_profile_guid: "C1DF3F68-8DBA-4918-A82A-ED0941A8787E" # guid in plist

  roles:
    - role: macos-apps
      when: ansible_os_family == 'Darwin'
    - role: common

  tasks:
    - name: Set default shell to {{ default_shell }}
      command: chsh -s {{ default_shell }}
      when: default_shell != current_shell

    - name: Ensure dotfiles are available from ~/.dotfiles
      file: src="{{ '../'| realpath }}" dest="{{ ansible_env.HOME }}/.dotfiles" state=link
      when: playbook_default_location != current_playbook_location

    - name: Create non-symlinked directories
      file: path="~/{{ item }}" state=directory
      with_items:
        - .atom
        - .vim
        - .zsh

    - name: Symlink to dotfiles
      file: src="{{ default_dotfiles }}/{{ item.from }}" dest="{{ item.to }}" state=link
      with_items:
        - from: zsh/zshrc
          to: ~/.zshrc
        - from: vim/vimrc
          to: ~/.vimrc
        - from: vim/vim/autoload
          to: ~/.vim/autoload
        - from: atom/config.cson
          to: ~/.atom/config.cson
        - from: emacs
          to: ~/.emacs.d

    - name: Install antigen for zsh
      git:  repo=https://github.com/zsh-users/antigen.git dest=~/.zsh/antigen

    ## GUI App configuration
    - name: Ensure iTerm2 dynamic profile directory exists
      file: path="~/Library/Application Support/iTerm2/DynamicProfiles" state=directory
      when: ansible_os_family == 'Darwin'

    - name: Symlink iTerm2 dynamic profile
      file: src="{{ default_dotfiles }}/iterm/default.json"
            dest="~/Library/Application Support/iTerm2/DynamicProfiles/default.json"
            state=link
      when: ansible_os_family == 'Darwin'

    - name: Check iTerm2 default profile
      command: defaults read com.googlecode.iterm2 "Default Bookmark Guid"
      register: iterm2_value
      when: ansible_os_family == 'Darwin'

    - name: Set iTerm2 default profile
      command: defaults write com.googlecode.iterm2 "Default Bookmark Guid" '{{ iterm2_profile_guid }}'
      when: ansible_os_family == 'Darwin' and "{{ iterm2_profile_guid }}" not in iterm2_value.stdout_lines

    - name: Check if atom package manager exists
      stat: path=/usr/local/bin/apm
      register: apm

    - name: Install atom editor packages
      command: apm install -q {{ item }} creates=~/.atom/packages/{{ item }}
      with_items:
        - atom-beautify
        - emmet
        - minimap
        - oceanic-next
        - pigments
        - sort-lines
      when: apm.stat.exists
